/**
 * Receipts routes — E2E encrypted payment receipts via Fileverse.
 *
 * Every payment creates a Fileverse document: a privacy-first receipt
 * that only the two parties involved can read. No bank, no Stripe,
 * no payment processor has access.
 *
 * The Fileverse satellite (localhost:8001) handles:
 *   - Client-side E2E encryption before documents leave the server
 *   - IPFS storage + Gnosis chain anchoring
 *   - Document accessibility via ddocs.new/<ddocId>
 *
 * Routes:
 *   POST /receipts        — create a receipt after a payment
 *   GET  /receipts        — list all receipts for the logged-in user
 */
const router  = require('express').Router();
const { requireAuth } = require('../middleware/auth');

const FILEVERSE_URL = process.env.FILEVERSE_API_URL || 'http://127.0.0.1:8001';
const FILEVERSE_KEY = process.env.FILEVERSE_API_KEY;

function fileverseHeaders() {
  return { 'Content-Type': 'application/json' };
}

function apiUrl(path) {
  return `${FILEVERSE_URL}${path}?apiKey=${FILEVERSE_KEY}`;
}

// ── Create receipt ────────────────────────────────────────────────────────────
// POST /receipts
// Body: { txHash, amount, chain, payerWalletId, receiverAddress, receiverEns? }
// Called immediately after a successful payment — fire-and-forget from the app.
router.post('/', requireAuth, async (req, res) => {
  if (!FILEVERSE_KEY) return res.status(503).json({ error: 'Fileverse not configured' });

  const { txHash, amount, chain, receiverAddress, receiverEns } = req.body;
  if (!txHash || !amount || !chain) {
    return res.status(400).json({ error: 'txHash, amount, chain are required' });
  }

  const to      = receiverEns || receiverAddress || 'unknown';
  const ts      = new Date().toISOString();
  const network = chain === 'ETH' ? 'Sepolia Testnet' : 'Devnet';
  const title   = `Receipt: ${amount} ${chain} — ${ts.slice(0, 10)}`;

  const markdown = [
    `# Payment Receipt`,
    ``,
    `| Field | Value |`,
    `|---|---|`,
    `| **Amount** | ${amount} ${chain} |`,
    `| **Network** | ${network} |`,
    `| **To** | ${to} |`,
    `| **Tx Hash** | \`${txHash}\` |`,
    `| **Timestamp** | ${ts} |`,
    `| **Auth** | NFC split-key authenticated |`,
    ``,
    `---`,
    `*End-to-end encrypted receipt generated by NFC Wallet.*`,
    `*No bank. No Stripe. No middlemen.*`,
  ].join('\n');

  try {
    const r = await fetch(apiUrl('/api/ddocs'), {
      method:  'POST',
      headers: fileverseHeaders(),
      body:    JSON.stringify({ title, fileContent: markdown }),
    });
    if (!r.ok) {
      const err = await r.text();
      return res.status(502).json({ error: `Fileverse error: ${err}` });
    }
    const data = await r.json();
    res.json({
      ddocId: data.ddocId ?? data._id ?? data.id,
      docUrl: `https://ddocs.new/${data.ddocId ?? data._id ?? data.id}`,
      title,
    });
  } catch (e) {
    console.error('Fileverse create:', e.message);
    res.status(500).json({ error: e.message });
  }
});

// ── List receipts ─────────────────────────────────────────────────────────────
// GET /receipts
router.get('/', requireAuth, async (req, res) => {
  if (!FILEVERSE_KEY) return res.status(503).json({ error: 'Fileverse not configured' });

  try {
    const r = await fetch(apiUrl('/api/ddocs'));
    if (!r.ok) return res.status(502).json({ error: 'Fileverse unavailable' });
    const data = await r.json();
    // data is an array of docs — return with ddocs.new URL added
    const docs = Array.isArray(data) ? data : (data.files ?? data.ddocs ?? []);
    res.json(docs.map(d => ({
      ddocId: d.ddocId ?? d._id ?? d.id,
      title:  d.title,
      docUrl: `https://ddocs.new/${d.ddocId ?? d._id ?? d.id}`,
      createdAt: d.createdAt,
    })));
  } catch (e) {
    console.error('Fileverse list:', e.message);
    res.status(500).json({ error: e.message });
  }
});

module.exports = router;
